# Generated by Django 5.2.6 on 2025-11-27 08:47

import accounts.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cenro_adminactionhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email address for verification and notifications', max_length=255, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('is_family_representative', models.BooleanField(default=False, help_text='Is this user the family representative?')),
                ('referral_code', models.CharField(blank=True, help_text='Unique code that others can use to get referral bonus', max_length=8, null=True, unique=True)),
                ('referred_by_code', models.CharField(blank=True, help_text='Code of the user who referred this user', max_length=8, null=True)),
                ('referral_bonus_awarded', models.BooleanField(default=False, help_text='Whether referral bonus has been awarded')),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-total_points', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_code', models.CharField(default=accounts.models.generate_family_code, max_length=12, unique=True)),
                ('family_name', models.CharField(help_text='Family surname or family identifier', max_length=100)),
                ('address', models.CharField(help_text='House No. and Street', max_length=255)),
                ('city', models.CharField(default='San Pedro City', max_length=100)),
                ('representative_name', models.CharField(help_text='Name of family member who registered', max_length=100)),
                ('representative_phone', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('total_members', models.IntegerField(default=0)),
                ('total_family_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
                'ordering': ['-total_family_points', 'family_name'],
            },
        ),
        migrations.CreateModel(
            name='GarbageSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('waste_types', models.JSONField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('user_agent', models.TextField(blank=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('waste', 'Waste Transaction'), ('redeem', 'Reward Redemption'), ('learning', 'Learning Video'), ('game', 'Game Points'), ('other', 'Other')], max_length=10)),
                ('message', models.TextField()),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reward_name', models.CharField(blank=True, max_length=255, null=True)),
                ('video_title', models.CharField(blank=True, max_length=255, null=True)),
                ('game_score', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When the notification was viewed by the user', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed')], max_length=10)),
                ('points_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, help_text='Number of items redeemed')),
                ('points_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redemption_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('points_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reward_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Reward Created'), ('updated', 'Reward Updated'), ('deleted', 'Reward Deleted'), ('stock_added', 'Stock Added'), ('stock_removed', 'Stock Removed'), ('stock_redeemed', 'Stock Redeemed')], max_length=20)),
                ('stock_change', models.IntegerField(default=0, help_text='Positive for additions, negative for reductions')),
                ('previous_stock', models.IntegerField(default=0)),
                ('new_stock', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the action')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Reward History',
                'verbose_name_plural': 'Reward Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which consent was given')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent for audit trail')),
            ],
            options={
                'verbose_name': 'User Consent',
                'verbose_name_plural': 'User Consents',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_kg', models.FloatField()),
                ('total_points', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('points_per_kg', models.DecimalField(decimal_places=2, help_text='Equivalent points per kilogram', max_digits=10)),
            ],
        ),
    ]
