# Generated by Django 5.2.6 on 2025-11-27 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cenro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenro.adminuser'),
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='family',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenro.adminuser'),
        ),
        migrations.AddField(
            model_name='family',
            name='barangay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barangay'),
        ),
        migrations.AddField(
            model_name='users',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.family'),
        ),
        migrations.AddField(
            model_name='garbageschedule',
            name='barangay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barangay'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', 'timestamp'], name='accounts_lo_ip_addr_4f26f9_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', 'timestamp'], name='accounts_lo_usernam_7bd469_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenro.adminuser'),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemption',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenro.adminuser'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemption',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.reward'),
        ),
        migrations.AddField(
            model_name='reward',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rewardcategory'),
        ),
        migrations.AddField(
            model_name='rewardhistory',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_actions', to='cenro.adminuser'),
        ),
        migrations.AddField(
            model_name='rewardhistory',
            name='redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.redemption'),
        ),
        migrations.AddField(
            model_name='rewardhistory',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.reward'),
        ),
        migrations.AddField(
            model_name='rewardhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='terms_version',
            field=models.ForeignKey(help_text='Version of terms that was accepted', on_delete=django.db.models.deletion.PROTECT, related_name='user_consents', to='cenro.termsandconditions'),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='user',
            field=models.ForeignKey(help_text='User who accepted the terms', on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastetransaction',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_transactions', to='accounts.barangay'),
        ),
        migrations.AddField(
            model_name='wastetransaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to='cenro.adminuser'),
        ),
        migrations.AddField(
            model_name='wastetransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastetransaction',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wastetype'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'viewed_at', '-created_at'], name='notif_user_viewed_idx'),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['user', '-accepted_at'], name='accounts_us_user_id_83ede5_idx'),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['terms_version', '-accepted_at'], name='accounts_us_terms_v_d21398_idx'),
        ),
        migrations.AddIndex(
            model_name='wastetransaction',
            index=models.Index(fields=['-created_at'], name='accounts_wa_created_669398_idx'),
        ),
        migrations.AddIndex(
            model_name='wastetransaction',
            index=models.Index(fields=['transaction_date'], name='accounts_wa_transac_8f7fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='wastetransaction',
            index=models.Index(fields=['barangay'], name='accounts_wa_baranga_c4f34c_idx'),
        ),
        migrations.AddIndex(
            model_name='wastetransaction',
            index=models.Index(fields=['waste_type'], name='accounts_wa_waste_t_987d1a_idx'),
        ),
    ]
