# Generated by Django 5.2.6 on 2025-11-27 08:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email address for notifications and credentials', max_length=255, null=True, unique=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('operations_manager', 'Operations Manager'), ('content_rewards_manager', 'Content & Rewards Manager'), ('security_analyst', 'Security & Reports Analyst')], default='operations_manager', max_length=30)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_controls', models.BooleanField(default=False)),
                ('can_manage_points', models.BooleanField(default=False)),
                ('can_manage_rewards', models.BooleanField(default=False)),
                ('can_manage_schedules', models.BooleanField(default=False)),
                ('can_manage_security', models.BooleanField(default=False)),
                ('can_manage_learning', models.BooleanField(default=False)),
                ('can_manage_games', models.BooleanField(default=False)),
                ('can_view_all', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=10)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_changed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('must_change_password', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admins', to='cenro.adminuser')),
                ('assigned_barangays', models.ManyToManyField(blank=True, help_text='Barangays this admin can manage', to='accounts.barangay')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenro.adminuser')),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_registration', 'New User Registration'), ('user_approved', 'User Approved'), ('user_rejected', 'User Rejected'), ('system_alert', 'System Alert'), ('admin_account_locked', 'Admin Account Locked'), ('admin_account_suspended', 'Admin Account Suspended'), ('admin_account_unlocked', 'Admin Account Unlocked'), ('admin_account_reactivated', 'Admin Account Reactivated'), ('barangay_assignment_changed', 'Barangay Assignment Changed')], default='system_alert', max_length=50)),
                ('message', models.TextField(help_text='Notification message text')),
                ('link_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_user', models.ForeignKey(blank=True, help_text='User related to this notification (e.g., newly registered user)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
                ('admin_user', models.ForeignKey(blank=True, help_text='Specific admin this notification is for (null = all admins)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='cenro.adminuser')),
                ('related_admin', models.ForeignKey(blank=True, help_text='Admin user this notification is about (for admin account events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_about_admin', to='cenro.adminuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', 'is_read', '-created_at'], name='cenro_admin_admin_u_6f3cd4_idx'), models.Index(fields=['is_read', '-created_at'], name='cenro_admin_is_read_3e9dab_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminActionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('create_admin', 'Create Admin'), ('approve_admin', 'Approve Admin'), ('reject_admin', 'Reject Admin'), ('suspend_admin', 'Suspend Admin'), ('unsuspend_admin', 'Unsuspend Admin'), ('reactivate_admin', 'Reactivate Admin'), ('edit_barangays', 'Edit Barangays'), ('lock_admin', 'Lock Admin'), ('unlock_admin', 'Unlock Admin'), ('view_users', 'View Users'), ('manage_controls', 'Manage Controls'), ('security_action', 'Security Action')], max_length=50)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_performed', to='cenro.adminuser')),
                ('target_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_received', to='cenro.adminuser')),
            ],
            options={
                'verbose_name': 'Admin Action History',
                'verbose_name_plural': 'Admin Action Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['admin_user', '-timestamp'], name='cenro_admin_admin_u_905e2c_idx'), models.Index(fields=['action', '-timestamp'], name='cenro_admin_action_66f521_idx'), models.Index(fields=['target_admin', '-timestamp'], name='cenro_admin_target__b86386_idx')],
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('english', 'English'), ('tagalog', 'Tagalog')], help_text='Language of the terms and conditions', max_length=10)),
                ('title', models.CharField(help_text='Title of the terms document', max_length=255)),
                ('version', models.CharField(help_text='Version number (e.g., 1.0, 2.1)', max_length=50)),
                ('content', models.TextField(help_text='Full text content of the terms and conditions')),
                ('file', models.FileField(blank=True, help_text='Optional: Upload PDF or DOC file', null=True, upload_to='terms_documents/')),
                ('is_active', models.BooleanField(default=False, help_text='Only one version per language can be active at a time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_created', to='cenro.adminuser')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_updated', to='cenro.adminuser')),
            ],
            options={
                'verbose_name': 'Terms and Conditions',
                'verbose_name_plural': 'Terms and Conditions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['language', 'is_active'], name='cenro_terms_languag_a2cab8_idx'), models.Index(fields=['-created_at'], name='cenro_terms_created_8d76ff_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('language', 'is_active'), name='unique_active_terms_per_language')],
            },
        ),
    ]
