# Generated by Django 5.2.6 on 2025-11-27 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, help_text='Unique device identifier from mobile app', max_length=255, unique=True)),
                ('device_name', models.CharField(help_text="User-friendly device name (e.g., 'My iPhone 13')", max_length=255)),
                ('device_type', models.CharField(help_text='Device type (ios/android)', max_length=50)),
                ('device_model', models.CharField(blank=True, help_text='Device model/brand', max_length=255)),
                ('os_version', models.CharField(blank=True, help_text='Operating system version', max_length=50)),
                ('app_version', models.CharField(blank=True, help_text='App version', max_length=50)),
                ('public_key', models.TextField(help_text='Device public key for biometric verification')),
                ('credential_id', models.CharField(db_index=True, help_text='Unique credential identifier for this biometric registration', max_length=500, unique=True)),
                ('device_fingerprint', models.CharField(help_text='Device fingerprint hash for additional security', max_length=255)),
                ('last_challenge', models.CharField(blank=True, help_text='Last authentication challenge sent to device', max_length=255, null=True)),
                ('challenge_expires_at', models.DateTimeField(blank=True, help_text='When the current challenge expires', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device is currently active')),
                ('is_trusted', models.BooleanField(default=False, help_text='Trusted devices skip additional verification')),
                ('failed_attempts', models.IntegerField(default=0, help_text='Failed authentication attempts counter')),
                ('max_failed_attempts', models.IntegerField(default=5, help_text='Max failed attempts before device lock')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for device registration', null=True)),
                ('registration_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Device',
                'verbose_name_plural': 'Biometric Devices',
                'db_table': 'biometric_devices',
                'ordering': ['-last_used_at', '-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricLoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('attempted_device_id', models.CharField(blank=True, help_text='Device ID used in attempt', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to='mobilelogin.biometricdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Login Attempt',
                'verbose_name_plural': 'Biometric Login Attempts',
                'db_table': 'biometric_login_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['user', 'is_active'], name='biometric_d_user_id_fd7bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['device_id', 'is_active'], name='biometric_d_device__ed1137_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['credential_id'], name='biometric_d_credent_ee21af_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricloginattempt',
            index=models.Index(fields=['user', '-attempted_at'], name='biometric_l_user_id_ef08f9_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricloginattempt',
            index=models.Index(fields=['device', '-attempted_at'], name='biometric_l_device__6c3b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricloginattempt',
            index=models.Index(fields=['success', '-attempted_at'], name='biometric_l_success_435bcb_idx'),
        ),
    ]
